### ISSUE TITLE
Add MAAP API server to GitLab rate-limit whitelist

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#443]
After enabling rate-limiting on GitLab ops, users are reporting errors when trying to register algorithms. Here is one example showing a 429 HTTP status code:

```
[Thu Sep 02 21:56:49.477895 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724] /var/www/maap-api-nasa/venv/lib/python3.6/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Thu Sep 02 21:56:49.477930 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]   InsecureRequestWarning)
[Thu Sep 02 21:56:49.534357 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724] Removing file : hysds-io.json.run_rebinning_ubuntu
[Thu Sep 02 21:56:49.592605 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724] Removing file : job-spec.json.run_rebinning_ubuntu
[Thu Sep 02 21:56:49.866550 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724] 2021-09-02 21:56:49,866 - api.maapapp - ERROR - Exception on /api/mas/algorithm [POST]
[Thu Sep 02 21:56:49.866584 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724] Traceback (most recent call last):
[Thu Sep 02 21:56:49.866588 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]   File "/var/www/maap-api-nasa/api/endpoints/algorithm.py", line 218, in post
[Thu Sep 02 21:56:49.866594 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]     algorithm_name=hysds.get_algorithm_file_name(algorithm_name))
[Thu Sep 02 21:56:49.866597 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]   File "/var/www/maap-api-nasa/api/utils/github_util.py", line 30, in update_git_repo
[Thu Sep 02 21:56:49.866601 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]     origin.push()
[Thu Sep 02 21:56:49.866605 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]   File "/var/www/maap-api-nasa/venv/lib/python3.6/site-packages/git/remote.py", line 844, in push
[Thu Sep 02 21:56:49.866610 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]     return self._get_push_info(proc, progress)
[Thu Sep 02 21:56:49.866614 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]   File "/var/www/maap-api-nasa/venv/lib/python3.6/site-packages/git/remote.py", line 730, in _get_push_info
[Thu Sep 02 21:56:49.866618 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]     proc.wait(stderr=stderr_text)
[Thu Sep 02 21:56:49.866621 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]   File "/var/www/maap-api-nasa/venv/lib/python3.6/site-packages/git/cmd.py", line 412, in wait
[Thu Sep 02 21:56:49.866625 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]     raise GitCommandError(self.args, status, errstr)
[Thu Sep 02 21:56:49.866628 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724] git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
[Thu Sep 02 21:56:49.866632 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]   cmdline: git push --porcelain origin
[Thu Sep 02 21:56:49.866650 2021] [wsgi:error] [pid 17757] [remote 35.162.142.31:49724]   stderr: 'fatal: unable to access 'https://oauth2:{gitlab-token}@repo.ops.maap-project.org/root/register-job.git/': The requested URL returned error: 429'
```

**Comment by bsatoriu** [comment]
I have disabled rate limiting on the Gitlab Ops server today to unblock UWG users, while I work on implementing this change.

**Comment by bsatoriu** [comment]
I ended up implementing Fail2Ban, on UAT only as a test. Gitlab's built-in rate-limiting feature does not support a IP allow-list as of yet, and the Rack Attack module is only applicable to git http authentication. 

With the Fail2Ban feature in place in UAT, you'll now get 'jailed' after two consecutive unsuccessful login attempts via the UI.
