### ISSUE TITLE
DPS job 403 permission error from s3://nasa-maap-data-store

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#445]
The following algorithm snippet runs fine in the ADE (Ops), but results in a 403 permission error when run from DPS:

source: https://repo.ops.maap-project.org/eguenther/PhoREAL/-/blob/master/source_code/icesatBin.py#L854
```python
    #Download ATL03
    #Setup the boto3 s3 session and the bucket, key, and output path
    s3path = args.atl03[0]

    import boto3
    aws_session = boto3.Session()
    s3 = aws_session.resource('s3')
    bucket_name = s3path.split("/")[2]
    s3_key = "/".join(s3path.split("/")[3:])
    print('result: ' + 's3://' + bucket_name + '/' + s3_key)
    print(s3path)
    output_dir = ""
    output_file = os.path.join(output_dir, os.path.basename(s3path))

    #Download
    s3.Bucket(bucket_name).download_file(s3_key, output_file)

```

Example DPS job results:

```
JobID: 	10de231a-609f-4f78-97f5-5a7a36d11be2
ProductName: 	traceback
Traceback: 	activate does not accept more than one argument:
['/app/PhoREAL/source_code/run_rebinning.sh', 's3://nasa-maap-data-store/file-staging/nasa-map/ATL03___004/2020.06.04/ATL03_20200604065433_10650706_004_01.h5', '/output']

+ /app/PhoREAL/source_code/run_rebinning.sh s3://nasa-maap-data-store/file-staging/nasa-map/ATL03___004/2020.06.04/ATL03_20200604065433_10650706_004_01.h5 /output
ls: cannot access 'input/ATL03*': No such file or directory
  WARNING: The script pyproj is installed in '/home/ops/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Traceback (most recent call last):
  File "/app/PhoREAL/source_code/icesatBin.py", line 928, in 
    main(args)
  File "/app/PhoREAL/source_code/icesatBin.py", line 869, in main
    s3.Bucket(bucket_name).download_file(s3_key, output_file)
  File "/home/ops/.local/lib/python3.8/site-packages/boto3/s3/inject.py", line 245, in bucket_download_file
    return self.meta.client.download_file(
  File "/home/ops/.local/lib/python3.8/site-packages/boto3/s3/inject.py", line 171, in download_file
    return transfer.download_file(
  File "/home/ops/.local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/home/ops/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/ops/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/ops/.local/lib/python3.8/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/ops/.local/lib/python3.8/site-packages/s3transfer/download.py", line 340, in _submit
    response = client.head_object(
  File "/home/ops/.local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ops/.local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
+ cp _stderr.txt _alt_traceback.txt
```

**Comment by sujen1412** [comment]
This update should fix the error. 
https://repo.ops.maap-project.org/eguenther/PhoREAL/-/commit/3ba6e6176b8f93cd27ff0c82e9f0daba40bd9d91

The problem was incorrect passing of variable values causing the s3 link to be constructed incorrectly.

**Comment by oddes** [comment]
@bsatoriu and @sujen1412  is this available to test in ops environment?

**Comment by sujen1412** [comment]
The problem was in the user code and nothing to do with the platform. 
So we have not made any code changes to the platform. 

So I dont know if its something you need to test from the platform side. But if you want to test running the user code let me know and I can get you in touch with the UWG member.
