### ISSUE TITLE
Fix MAAP API 500 error for certain granules

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#676]
The following granule download results in a 500 error:

```
# import the maap package to handle queries
from maap.maap import MAAP
# invoke the MAAP using the MAAP host argument
maap = MAAP(maap_host='api.ops.maap-project.org')
# search for granule data using CMR host name, collection concept ID, and Granule UR arguments
results = maap.searchGranule(
    cmr_host='cmr.earthdata.nasa.gov',
    short_name='GEDI02_A')
# download first result
download = results[0].getData()
```

Corresponding API error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/gedi_subset/lib/python3.10/site-packages/maap/Result.py", line 64, in getData
    return self._getHttpData(url, overwrite, dest)
  File "/opt/conda/envs/gedi_subset/lib/python3.10/site-packages/maap/Result.py", line 105, in _getHttpData
    r.raise_for_status()
  File "/opt/conda/envs/gedi_subset/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://api.ops.maap-project.org/api/cmr/granules/https%253A%252F%252Fe4ftl01.cr.usgs.gov%252F%252FGEDI_L1_L2%252FGEDI%252FGEDI02_A.002%252F2019.04.18%252FGEDI02_A_2019108002012_O01959_01_T03909_02_003_01_V002.h5/data
```

**Comment by bsatoriu** [comment]
This is patched and ready to test on Ops.

**Comment by oddes** [comment]
Works as expected. Dowloaded files as expected:

![Screenshot 2023-03-05 at 6.22.52 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/5911f192-791b-46d9-ae35-5bdf72cd72dc)
